# Generated by Django 5.0.1 on 2024-01-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('priority', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('est_time', models.CharField(max_length=50)),
                ('due_date', models.CharField(max_length=50)),
            ],
        ),
    ]
