# Generated by Django 5.0.1 on 2024-01-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_task_due_date_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(models.Case(models.When(priority=1, then=models.Value(1)), models.When(priority=2, then=models.Value(2)), models.When(priority=3, then=models.Value(3))), models.F('priority'), name='priority_order'),
        ),
    ]
