# Generated by Django 5.0.1 on 2024-01-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_task_priority_order_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'To-Do'), ('2', 'In Progress'), ('3', 'Completed')], max_length=20, null=True),
        ),
    ]
